#!/bin/bash

# install this in the .todo.actions.d folder of your todo.txt CLI install.

# by Maarten van Gompel (proycon) proycon@anaproy.nl
# GNU Public License v3

action=$1
shift

[ "$action" = "usage" ] && {
  echo "  Action menu:"
  echo "    actionmenu"
  echo "      Shows or processing items for the action menu, not meant to be used directly"
  echo "    actionmenu [action] [itemno] [-d]"
  echo "      Run the action on the item number. Add -d (at the end) to act on done.txt"
  echo ""
  exit
}

if [ $# -eq 0 ]; then
echo -e "0 - Start task (track in log)
1 - Mark as done
2 - Increase priority
3 - Decrease priority
4 - Remove priority
5 - Edit
6 - View issue/mail
8 - Print to output
9 - Append extra info
A - Set priority A
B - Set priority B
C - Set priority C
D - Set priority D (waiting/blocked)
q - Quit"
else
    action=$1
    itemno=$2
    extra=$3
    if [ -n "$extra" ] && [ "$extra" != "-d" ]; then
        echo "Third parameter may only be -d, got $extra">&2
        exit 1
    fi

    if [ -z "$action" ]; then
        echo "No action passed">&2
        exit 1
    fi
    if [ -z "$itemno" ]; then
        echo "No item number passed">&2
        exit 1
    fi
    case $action in
        0|timetrack)
            echo "Starting timetrack">&2
            $TODO_FULL_SH timetrack start $itemno
            exit 10 #signal for rofi/fzf handler to exit after
            ;;
        1|done)
            echo "Marking as done">&2
            $TODO_FULL_SH more done $itemno
            exit 10
            ;;
        2|priup)
            echo "Increasing priority">&2
            $TODO_FULL_SH priup $itemno
            ;;
        3|pridown)
            echo "Decreasing priority">&2
            $TODO_FULL_SH pridown $itemno
            ;;
        4|depri)
            echo "Removing priority">&2
            $TODO_FULL_SH depri $itemno
            if [ "$TODOTXT_NOTIFY" = 1 ]; then
                item="$($TODO_FULL_SH show $itemno)"
                notify-send -a "todo.txt-more" "Task priority removed" "$item"
            fi
            ;;
        5|edit)
            echo "Running editor">&2
            $TODO_FULL_SH edit $itemno
            exit 10
            ;;
        6|view)
            echo "Viewing issue/mail">&2
            $TODO_FULL_SH more view $itemno $extra
            exit 10
            ;;
        7)
            $TODO_FULL_SH format show $extra $itemno
            ;;
        9|append)
            $TODO_FULL_SH listproj > /tmp/todo.projects.txt
            $TODO_FULL_SH listcon >> /tmp/todo.projects.txt
            echo "due:$(date +"%Y-%m-%d %a")" >> /tmp/todo.projects.txt
            echo "due:$(date --date tomorrow +"%Y-%m-%d %a")" >> /tmp/todo.projects.txt
            for i in $(seq 2 30); do
                echo "due:$(date --date "$i days" +"%Y-%m-%d %a")" >> /tmp/todo.projects.txt
            done
            EXTRA=$(cat /tmp/todo.projects.txt | rofi -matching glob -tokenize -i -no-sort -no-levenshtein-sort -markup -markup-rows -dmenu -p "NEW>" -mesg "Extra project/context to add to task" | cut -d" " -f 1)
            if [ -n "$EXTRA" ]; then
                if [ -n "$TODOTXT_INFERMAP" ]; then
                    EXTRA=$("$SCRIPTDIR/helpers/infer.py" "$TODOTXT_INFERMAP" "$EXTRA")
                fi
                $TODO_FULL_SH append "$itemno" "$EXTRA"
            fi
            ;;
        A)
            echo "Setting priority">&2
            $TODO_FULL_SH pri $itemno A
            ;;
        B)
            echo "Setting priority">&2
            $TODO_FULL_SH pri $itemno B
            ;;
        C)
            echo "Setting priority">&2
            $TODO_FULL_SH pri $itemno C
            ;;
        D)
            echo "Setting priority">&2
            $TODO_FULL_SH pri $itemno D
            ;;
        q)
            exit 0
            ;;
        *)
            echo "Unknown action: $action">&2
            ;;
    esac
fi

