#!/bin/bash

#install this in the .todo.actions.d folder of your todo.txt CLI install.

action=$1
shift

SCRIPTDIR="$(dirname $0)"

[ "$action" = "usage" ] && {
  echo "  Auto prioritisation:"
  echo "    autoprio"
  echo "      automatically assign priorities where possible"
  echo ""
  exit
}

"$SCRIPTDIR/helpers/autoprio.py" "$TODO_FILE"
