#!/bin/bash

#install this in the .todo.actions.d folder of your todo.txt CLI install.

action=$1
shift

SCRIPTDIR="$(dirname $0)"

[ -z "$TODO_ISSUE_OPENER" ] && TODO_ISSUE_OPENER=xdg-open

[ "$action" = "usage" ] && {
  echo "  calendar support:"
  echo "    cal import [[--edit]] [filename]"
  echo "      imports an ics file. Takes care not to import duplicates. filename may also be - for stdin"
  echo "      add the -e option if you want to edit the item immediately after adding (to add tags etc)"
  echo "    cal export [itemno] .."
  echo "      export the specified item numbers to ics (to stdout)"
  echo "    cal list [[--headers|-H]"
  echo "      list all calendar items, add --headers to output headers (ansi colours only)"
  echo "    cal"
  echo "      shortcut for cal list --headers"
  echo ""
  exit
}


getduedate() {
    echo "$1" | grep -Po "due:\\d\\d\\d\\d-\\d\\d-\\d\\d" | sed 's/due://'
}

if [ $# -eq 0 ]; then
    set -- list --headers
fi

if [ "$1" = "import" ]; then
    if [ "$1" = "-e" ] || [ "$1" == "--edit" ]; then
        shift
        edit=1
    else
        edit=0
    fi
    shift
    filename=$1
    if [ ! -e "$filename" ]; then
        echo "no such file to import: $filename"
    fi
    if cat "$filename" | "$SCRIPTDIR/helpers/icsimport.py" -t "$TODO_FILE" -d "$DONE_FILE"; then
        item="$(tail -n 1 "$TODO_FILE")"
        [ "$TODOTXT_NOTIFY" = 1 ] && notify-send -a "todo.txt-more" "Calendar task added" "$item"
        [ $edit -eq 1 ] && $TODO_FULL_SH edit 999999
    else
        if [ $? -eq 2 ]; then
            [ "$TODOTXT_NOTIFY" = 1 ] && notify-send -a "todo.txt-more" "Calendar item already exists"
        else
            [ "$TODOTXT_NOTIFY" = 1 ] && notify-send -a "todo.txt-more" "Failed to add calendar item"
        fi
    fi
elif [ "$1" = "export" ]; then
    shift
    "$SCRIPTDIR/helpers/icsexport.py" -t "$TODO_FILE" $@
elif [ "$1" = "list" ]; then
    shift
    if [ "$1" = "-H" ] || [ "$1" == "--headers" ]; then
        shift
        $TODO_FULL_SH more list "@calendar" $@ | sed -r 's/\@calendar//' | while read line; do
            duedate=$(getduedate "$line")
            if [ "$duedate" != "$prevduedate" ]; then
                echo
                echo -e "\033[32;1m$duedate -- $(date --date="$duedate" +"%A %e %B %Y")\033[0m"
                echo
            fi
            echo -e "$line" | sed -r "s/due:${duedate}T?//g"
            prevduedate="$duedate"
        done
    else
        $TODO_FULL_SH more list "@calendar" $@ | sed -r 's/\@calendar//'
    fi
fi

