#!/bin/bash

# install this in the ~/.todo.actions.d dir 

# by Maarten van Gompel (proycon) proycon@anaproy.nl
# GNU Public License v3

WORD_REGEX="[[:alnum:]]+"

action=$1
shift

[ "$action" = "usage" ] && {
  echo "  Fuzzy search:"
  echo "    fzf [ACTIONS]"
  echo "      pass actions through fzf and make them actionable"
  echo ""
  exit
}

if [ $# -eq 0 ]; then
    set -- list
fi

itemno=""
while true; do
    itemno=$($TODO_FULL_SH format "$@" | fzf --ansi --no-hscroll --layout reverse | grep -P "\d+ .*$" | cut -d" " -f 1)
    if [ -n "$itemno" ]; then
        item=$($TODO_FULL_SH format show "$itemno")
        action=$($TODO_FULL_SH actionmenu | fzf --header "$item" --layout reverse | grep -P "[\dABCq] .*" | cut -d" " -f 1) 
        if [ "$action" = "q" ] || [ -z "$action" ]; then
            break
        fi
        if ! $TODO_FULL_SH actionmenu "$action" "$itemno"; then
            break
        fi
        sleep 1
    else
        break
    fi
done

