#!/bin/bash

#install this in the .todo.actions.d folder of your todo.txt CLI install.

action=$1
shift

SCRIPTDIR="$(dirname $0)"

[ -z "$TODO_ISSUE_OPENER" ] && TODO_ISSUE_OPENER=xdg-open

[ "$action" = "usage" ] && {
  echo "  Handle linked issues:"
  echo "    issue [[-d]] [itemno]"
  echo "      view the issue referenced in the item (if any). Add -d to search in done tasks"
  echo "    issue sync"
  echo "      sync issues from remote"
  echo "    issue close|done [itemno] ..."
  echo "      close the reference issue (and mark the item as a whole as done)"
  echo ""
  exit
}

geturl() {
    sed -n "${1}p" "$target" | grep -Po "issue:http[^[:blank:]]+" | sed 's/issue://'
}

if [ "$1" = "-d" ]; then
    shift
    target=$DONE_FILE
else
    target=$TODO_FILE
fi

[ -n "$TODOTXT_INFERMAP" ] && export TODO_ISSUE_INFERMAP="$TODOTXT_INFERMAP"


if [ "$1" = "sync" ]; then
    extra=""
    [ "$TODOTXT_NOTIFY" = "1" ] && notify-send -a "todo.txt-more" "Issue sync" "Starting..."
    [ -n "$TODO_ISSUE_LABELMAP" ] && extra="-l $TODO_ISSUE_LABELMAP"
    [ -n "$TODO_ISSUE_INFERMAP" ] && extra="$extra -i $TODO_ISSUE_INFERMAP"
    if "$SCRIPTDIR/helpers/issuesync.py" -t "$TODO_FILE" -d "$DONE_FILE" $extra; then
        [ "$TODOTXT_NOTIFY" = "1" ] && notify-send -a "todo.txt-more" "Issue sync" "Done"
    else
        msg="Unable to sync issues. Did you set \$GITHUB_TOKEN?"
        echo "$msg" >&2
        [ "$TODOTXT_NOTIFY" = "1" ] && notify-send -a "todo.txt-more" "Issue sync" "$msg"
    fi
elif [ "$1" = "done" ] || [ "$1" = "do" ] || [ "$1" = "close" ] || [ "$1" = "c" ]; then
    while [ "$#" -gt 0 ] ; do
        itemno=$1
        url=$(geturl $itemno)
        shift
        item="$($TODO_FULL_SH show $itemno)"
        $TODO_FULL_SH done "$itemno"
        if echo "$url" | grep -q "github.com" && [ -n "$GITHUB_TOKEN" ]; then
            curl \
              -X PATCH \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer $GITHUB_TOKEN"\
              -H "X-GitHub-Api-Version: 2022-11-28" \
              "$(echo "$url" | sed -e 's/https:\/\/github.com\//https:\/\/api.github.com\/repos\//')" \
              -d '{"state":"closed"}'
            [ "$TODOTXT_NOTIFY" = "1" ] && notify-send -a "todo.txt-more" "Task/issue closed" "$item"
        else
            [ "$TODOTXT_NOTIFY" = "1" ] && notify-send -a "todo.txt-more" "Task done (issue untouched)" "$item"
        fi
    done
else
    [ "$1" = "view" ] && shift
    itemno=$1
    url=$(geturl "$itemno")
    if [ -n "$url" ]; then
        [ "$TODOTXT_NOTIFY" = "1" ] && notify-send -a "todo.txt-more" "Opening issue in viewer" "$url"
        $TODO_ISSUE_OPENER "$url"
    else
        msg="No issue found"
        echo "$msg">&2
        [ "$TODOTXT_NOTIFY" = "1" ] && notify-send -a "todo.txt-more" "Error" "$msg"
    fi
fi

