#!/bin/bash

#install this in the .todo.actions.d folder of your todo.txt CLI install.

action=$1
shift

SCRIPTDIR="$(dirname $0)"

[ -z "$TODO_ISSUE_OPENER" ] && TODO_ISSUE_OPENER=xdg-open

[ "$action" = "usage" ] && {
  echo "  Handle linked issues:"
  echo "    issue [[-d]] [itemno]"
  echo "      view the issue referenced in the item (if any). Add -d to search in done tasks"
  echo "    issue sync"
  echo "      sync issues from remote"
  echo "    issue close [itemno] ..."
  echo "      close the reference issue (and the item as a whole)"
  echo ""
  exit
}

geturl() {
    sed -n "${1}p" "$target" | grep -Po "issue:http[^[:blank:]]+" | sed 's/issue://'
}

if [ "$1" = "-d" ]; then
    shift
    target=$DONE_FILE
else
    target=$TODO_FILE
fi

if [ "$1" = "sync" ]; then
    extra=""
    [ -n "$TODO_ISSUE_LABELMAP" ] && extra="-l $TODO_ISSUE_LABELMAP"
    [ -n "$TODO_ISSUE_INFERMAP" ] && extra="$extra -i $TODO_ISSUE_INFERMAP"
    "$SCRIPTDIR/issuesync.py" -t "$TODO_FILE" -d "$DONE_FILE" $extra
elif [ "$1" = "close" ] || [ "$1" = "c" ]; then
    while [ "$#" -gt 0 ] ; do
        itemno=$1
        shift
        $TODO_FULL_SH done "$itemno"
    done
else
    itemno=$1
    url=$(geturl "$itemno")
    if [ -n "$url" ]; then
        $TODO_ISSUE_OPENER "$url"
    else
        echo "No issue found">&2
    fi
fi

