#!/bin/bash

#install this in the .todo.actions.d folder of your todo.txt CLI install.

action=$1
shift

[ "$action" = "usage" ] && {
  echo "  Priority changing:"
  echo "    pridown [itemno]"
  echo "      Decreases the priority of the item number, deprioritize after C"
  echo ""
  exit
}

if [ "$1" = "-d" ]; then
    shift
    target=$DONE_FILE
else
    target=$TODO_FILE
fi

while [ "$#" -gt 0 ] ; do
    itemno=$1
    shift
    sed -i -r "${itemno}s/^\(C\)//; ${itemno}s/^\(B\)/(C)/; ${itemno}s/^\(A\)/(B)/" "$target" 
    if [ "$TODOTXT_NOTIFY" = 1 ]; then
        item="$($TODO_FULL_SH show $itemno)"
        notify-send -a "todo.txt-more" "Task priority decreased" "$item"
    fi
done
