#!/bin/bash

#install this in the .todo.actions.d folder of your todo.txt CLI install.

action=$1
shift

[ "$action" = "usage" ] && {
  echo "  Decrease priority of item, deprioritize after C:"
  echo "    show [[-d]] [itemno]"
  echo "      show the task on the specified line. Add -d to search in done tasks"
  echo ""
  exit
}

if [ "$1" == "-d" ]; then
    shift
    target=$DONE_FILE
else
    target=$TODO_FILE
fi

while [ "$#" -gt 0 ] ; do
    item=$1
    shift
    sed -i -r "${item}s/^\(C\)//; ${item}s/^\(B\)/(C)/; ${item}s/^\(A\)/(B)/" "$target" 
done
