#!/bin/bash

#install this in the .todo.actions.d folder of your todo.txt CLI install.

action=$1
shift

[ "$action" = "usage" ] && {
  echo "  Priority changing:"
  echo "    priup [itemno]"
  echo "      Increase the priority of the item number, unprioritized becomes C"
  echo ""
  exit
}

if [ "$1" = "-d" ]; then
    shift
    target=$DONE_FILE
else
    target=$TODO_FILE
fi

while [ "$#" -gt 0 ] ; do
    itemno=$1
    shift
    sed -i -r "${itemno}s/^\(B\)/(A)/; ${itemno}s/^\(C\)/(B)/; ${itemno}s/^([^\(])/(C) \1/" "$target" 
done
