#!/bin/bash

# install this in the .todo.actions.d folder of your todo.txt CLI install.

# by Maarten van Gompel (proycon) proycon@anaproy.nl
# GNU Public License v3

striptags() {
    sed -e 's/<[^>]*>//g'
}

action=$1
shift

[ "$action" = "usage" ] && {
  echo "  Fuzzy search:"
  echo "    rofi [ACTIONS]"
  echo "      pass actions through rofi and make them actionable"
  echo ""
  exit
}

if [ $# -eq 0 ]; then
    set -- list
fi

itemno=""
while true; do
    itemno=$($TODO_FULL_SH color pango "$@" | rofi -matching glob -tokenize -i -no-levenshtein-sort -markup -markup-rows -dmenu -p ">" -mesg "todo.txt" | striptags | grep -Po "\d+ .*$" | cut -d" " -f 1)
    if [ -n "$itemno" ]; then
        item=$($TODO_FULL_SH color pango show "$itemno")
        action=$($TODO_FULL_SH actionmenu | rofi -matching glob -tokenize -i -no-levenshtein-sort -markup -markup-rows -dmenu -mesg "$item" | striptags | grep -P "[\dABCq] .*" | cut -d" " -f 1) 

        if [ "$action" = "q" ] || [ -z "$action" ]; then
            break
        fi
        $TODO_FULL_SH actionmenu "$action" "$itemno"
        sleep 1
    else
        break
    fi
done

