#!/bin/bash

# install this in the ~/.todo.actions.d dir 

# by Maarten van Gompel (proycon) proycon@anaproy.nl
# GNU Public License v3

striptags() {
    sed -e 's/<[^>]*>//g'
}

action=$1
shift

[ "$action" = "usage" ] && {
  echo "  Fuzzy search:"
  echo "    rofi [ACTIONS]"
  echo "      pass actions through rofi and make them actionable"
  echo ""
  exit
}

if [ $# -eq 0 ]; then
    set -- list
fi

[ -z $TERMINAL_CMD ] && export TERMINAL_CMD="foot -e"
[ -z "$TIMETRACK_FILE" ] && TIMETRACK_FILE="$TODO_DIR/timetrack.txt"

itemno=""
while true; do
    result=$($TODO_FULL_SH relsort "$@" | $TODO_FULL_SH format pango stdin | rofi -matching glob -tokenize -i -no-sort -no-levenshtein-sort -markup -markup-rows -dmenu -p ">" -mesg "todo.txt - <span fgcolor=\"gray\">alt-e = edit, alt-a = add and timetrack, alt-d = done, alt-k = priup, alt-j = pridown, alt-t = edit timetrack</span>" -kb-custom-1 "Alt-a" -kb-custom-2 "Alt-e" -kb-custom-3 "Alt-d" -kb-custom-4 "Alt-j" -kb-custom-5 "Alt-k" -kb-custom-6 "Alt-t")
    ret=$?
    itemno=$(echo "$result" | striptags | grep -Po "\d+ .*$" | cut -d" " -f 1)
    case $ret in
        10)
            $TODO_FULL_SH add "$result"
            $TODO_FULL_SH timetrack start "$result"
            break
            ;;
        11)
            $TERMINAL_CMD $TODO_FULL_SH edit "$itemno"
            break
            ;;
        12)
            $TODO_FULL_SH done "$itemno"
            ;;
        14)
            $TODO_FULL_SH priup "$itemno"
            ;;
        13)
            $TODO_FULL_SH pridown "$itemno"
            ;;
        15)
            $TERMINAL_CMD $EDITOR +999999 "$TIMETRACK_FILE"
            ;;
        0)
            if [ -n "$itemno" ]; then
                item=$($TODO_FULL_SH format pango show "$itemno")
                action=$($TODO_FULL_SH actionmenu | rofi -matching glob -tokenize -i -no-levenshtein-sort -markup -markup-rows -dmenu -mesg "$item" | striptags | grep -P "[\dABCq] .*" | cut -d" " -f 1) 

                if [ "$action" = "q" ] || [ -z "$action" ]; then
                    break
                fi
                if ! $TODO_FULL_SH actionmenu "$action" "$itemno"; then
                    break
                fi
                sleep 1
            else
                #add new item
                $TODO_FULL_SH add "$result"
            fi
            ;;
        *)
            break
    esac
done

